Enable LOGURU_STACKTRACES cmake var by default on glibc
Changes:
- Fixes issue [#248](https://github.com/emilk/loguru/issues/248)
- CMake now performs a quick `try_run()` to inspect whether the
  currently detected C++ compiler is using glibc, and if so sets the
  LOGURU_STACKTRACES variable to TRUE by default to match the default
  value of the LOGURU_STACKTRACES macro inside `loguru.cpp`.

Notes:
- This is required because the cmake file is currently setup to only
  link loguru to the `dl` library if the cmake variable
  LOGURU_STACKTRACES is TRUE.
  Unfortunately, the `loguru.cpp` file implicitly enables the
  stacktraces feature under certain conditions (glibc on non-windows)
  and the CMake file wasn't previously written to account for that.
  This meant that the `dl` library wasn't being linked even though
  stacktraces were enabled (in the .cpp file), causing a linking error.
  - `undefined reference to `dladdr'`